#!/usr/bin/env python3
"""Bakes assets/cat-sheet.png into hooks/register.tsx, between the sprite markers.

The hooks module has no image decoder and reads no file while drawing, so the
sheet rides in the source: a palette, and one string a frame, one character a
pixel (`.` is transparent). Run it again whenever the sheet changes.
"""
import json, os, subprocess, sys

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sheet = json.load(open(os.path.join(root, 'assets', 'cat-sheet.json')))
width, height = sheet['frameWidth'], sheet['frameHeight']
across = sheet['columns'] * width
raw = subprocess.run(
    ['magick', os.path.join(root, 'assets', sheet['image']), '-depth', '8', 'rgba:-'],
    capture_output=True, check=True).stdout
assert len(raw) == across * sheet['rows'] * height * 4, 'the sheet is not the size its manifest says'

LETTERS = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
palette = []


def letter(x, y):
    at = (y * across + x) * 4
    r, g, b, a = raw[at:at + 4]
    if a < 128:
        return '.'
    color = f'#{r:02x}{g:02x}{b:02x}'
    if color not in palette:
        palette.append(color)
    return LETTERS[palette.index(color)]


clips = []
for one in sheet['animations']:
    frames = []
    for k in range(one['frames']):
        frames.append(''.join(
            letter(k * width + x, one['row'] * height + y) for y in range(height) for x in range(width)))
    clips.append((one['name'], one['frameDurationMs'], frames))

out = ['// <sprites> generated by scripts/build-sprites.py from assets/cat-sheet.png — do not edit',
       f'const SPRITE_W = {width}', f'const SPRITE_H = {height}',
       f"const SPRITE_INK = '{LETTERS[:len(palette)]}'",
       'const SPRITE_PALETTE = [' + ', '.join(f'0x{c[1:]}' for c in palette) + ']',
       'const CLIPS = {']
for name, ms, frames in clips:
    out.append(f'  {name}: {{')
    out.append(f'    ms: {ms},')
    out.append('    frames: [')
    out += [f"      '{frame}'," for frame in frames]
    out.append('    ],')
    out.append('  },')
out += ['} as const', '// </sprites>']

path = os.path.join(root, 'hooks', 'register.tsx')
source = open(path, encoding='utf-8').read()
start, end = source.index('// <sprites>'), source.index('// </sprites>') + len('// </sprites>')
open(path, 'w', encoding='utf-8').write(source[:start] + '\n'.join(out) + source[end:])
print(f'{sum(len(f) for _, _, f in clips)} frames, {len(palette)} colors')
