#!/usr/bin/env python3
"""Bakes the cat sheets into hooks/register.tsx, between the sprite markers.

The hooks module has no image decoder and reads no file while drawing, so the
sheets ride in the source: a palette, and one string a frame, one character a
pixel (`.` is transparent). Run it again whenever a sheet changes. The decor
sheet, assets/decor/decor-sheet.png, is baked the same way, an entry an element.

Each cat under assets/cats/<name>/ has a 64x36 sheet, `cat-sheet.png`, drawn
big: 64 columns by 18 rows, in half blocks, one pixel a half cell. Its small
size is `cat-sheet-small.png` where the cat has one drawn for it, else the big
sheet sampled down by half. A cat with no big sheet of its own names another's
in BORROWS.
"""
import base64, json, os, subprocess

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
cats = os.path.join(root, 'assets', 'cats')
LETTERS = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
ORDER = ['roux', 'noir', 'garfield', 'panda']
# garfield is the first 64x36 orange sheet; small, it is the roux cat's own.
BORROWS = {('garfield', 'small'): os.path.join(cats, 'roux', 'cat-sheet-small.json')}


def bake(manifest, halve=False):
    sheet = json.load(open(manifest))
    width, height = sheet['frameWidth'], sheet['frameHeight']
    sample = []
    if halve:
        width, height, sample = width // 2, height // 2, ['-sample', '50%']
    across = sheet['columns'] * width
    raw = subprocess.run(
        ['magick', os.path.join(os.path.dirname(manifest), sheet['image']), *sample, '-depth', '8', 'rgba:-'],
        capture_output=True, check=True).stdout
    assert len(raw) == across * sheet['rows'] * height * 4, f'{manifest}: not the size its manifest says'
    palette = []

    def letter(x, y):
        at = (y * across + x) * 4
        r, g, b, a = raw[at:at + 4]
        if a < 128:
            return '.'
        color = f'{r:02x}{g:02x}{b:02x}'
        if color not in palette:
            palette.append(color)
        return LETTERS[palette.index(color)]

    clips = []
    for one in sheet['animations']:
        clips.append(f"        {one['name']}: {{")
        clips.append(f"          ms: {one['frameDurationMs']},")
        clips.append('          frames: [')
        for k in range(one['frames']):
            frame = ''.join(letter(k * width + x, one['row'] * height + y) for y in range(height) for x in range(width))
            clips.append(f"            '{frame}',")
        clips += ['          ],', '        },']
    # The sheet itself, stripped of its metadata: what a surface that draws real
    # pictures (the desktop's Svg) is handed in place of the baked pixels.
    png = subprocess.run(
        ['magick', os.path.join(os.path.dirname(manifest), sheet['image']), *sample, '-strip', 'png:-'],
        capture_output=True, check=True).stdout
    return [f'      w: {width},', f'      h: {height},', f"      ink: '{LETTERS[:len(palette)]}',",
            f"      across: {sheet['columns']},", f"      down: {sheet['rows']},",
            f"      png: '{base64.b64encode(png).decode()}',",
            '      palette: [' + ', '.join(f'0x{c}' for c in palette) + '],', '      clips: {', *clips, '      },']


lines = ['// <sprites> generated by scripts/build-sprites.py from the sheets under assets/cats/ — do not edit',
         'const SHEETS = {']
for name in ORDER:
    home = os.path.join(cats, name)
    big = os.path.join(home, 'cat-sheet.json')
    small = BORROWS.get((name, 'small'), os.path.join(home, 'cat-sheet-small.json'))
    lines.append(f'  {name}: {{')
    lines += ['    small: {', *(bake(small) if os.path.exists(small) else bake(big, halve=True)), '    },']
    lines += ['    big: {', *bake(big), '    },']
    lines.append('  },')
    print(f'{name}: baked')
lines += ['} as const', '// </sprites>']



def bake_decor():
    """The decor sheet, one entry an element: its frames as strings, as the cats' are."""
    home = os.path.join(root, 'assets', 'decor')
    sheet = json.load(open(os.path.join(home, 'decor-sheet.json')))
    across = sheet['width']
    raw = subprocess.run(['magick', os.path.join(home, sheet['image']), '-depth', '8', 'rgba:-'],
                         capture_output=True, check=True).stdout
    assert len(raw) == across * sheet['height'] * 4, 'the decor sheet is not the size its manifest says'
    palette = []

    def letter(x, y):
        at = (y * across + x) * 4
        r, g, b, a = raw[at:at + 4]
        if a < 128:
            return '.'
        color = f'{r:02x}{g:02x}{b:02x}'
        if color not in palette:
            palette.append(color)
        return LETTERS[palette.index(color)]

    items = []
    for one in sheet['elements']:
        frames = [''.join(letter(one['x'] + k * one['w'] + x, one['y'] + y)
                          for y in range(one['h']) for x in range(one['w'])) for k in range(one['frames'])]
        box = one['bbox']
        items.append(f"    {one['name']}: {{ at: [{one['x']}, {one['y']}], w: {one['w']}, h: {one['h']}, ms: {one['frameDurationMs'] or 1}, "
                     f"box: [{box['x']}, {box['y']}, {box['w']}, {box['h']}], frames: ["
                     + ', '.join(f"'{frame}'" for frame in frames) + '] },')
    png = subprocess.run(['magick', os.path.join(home, sheet['image']), '-strip', 'png:-'],
                         capture_output=True, check=True).stdout
    print(f"decor: {len(items)} elements, {len(palette)} colors")
    return ['// <decor> generated by scripts/build-sprites.py from assets/decor/ — do not edit',
            'const DECOR = {', f"  ink: '{LETTERS[:len(palette)]}',",
            f"  sheet: [{sheet['width']}, {sheet['height']}],", f"  png: '{base64.b64encode(png).decode()}',",
            '  palette: [' + ', '.join(f'0x{c}' for c in palette) + '],', '  items: {', *items, '  },',
            '} as const', '// </decor>']


path = os.path.join(root, 'hooks', 'register.tsx')
source = open(path, encoding='utf-8').read()
start, end = source.index('// <sprites>'), source.index('// </sprites>') + len('// </sprites>')
source = source[:start] + '\n'.join(lines) + source[end:]
start, end = source.index('// <decor>'), source.index('// </decor>') + len('// </decor>')
open(path, 'w', encoding='utf-8').write(source[:start] + '\n'.join(bake_decor()) + source[end:])
